build_app:
  stage: build
  script:
    - docker build -t danieleff/nextrocket.space .
    - docker push danieleff/nextrocket.space

deploy_app:
  stage: deploy
  script:
    - "scp -o StrictHostKeyChecking=no docker-compose.yml nextrocket@danieleff.com:~/"
    - "ssh -o StrictHostKeyChecking=no nextrocket@danieleff.com 'docker-compose pull'"
    - "ssh -o StrictHostKeyChecking=no nextrocket@danieleff.com 'docker-compose up -d --no-build --force-recreate'"
